import streamlit as st
from pinecone import Pinecone
from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()

def get_secret(key):
    try:
        return st.secrets[key]
    except:
        return os.getenv(key)

# Initialize clients
pc = Pinecone(api_key=get_secret("PINECONE_KEY"))
index = pc.Index("amazon-reviews-rag")
llm = OpenAI(api_key=get_secret("DEEPSEEK_API_KEY"), base_url="https://api.deepseek.com")


#---------------------------------------------------------------------------
st.title("🔍 Amazon Review Assistant")
st.markdown("Ask anything about customer complaints from Amazon reviews.")
st.caption("Data source: 1,545 negative Amazon product reviews. Clusters generated by HDBSCAN.")

if "query_count" not in st.session_state:
    st.session_state.query_count = 0

if st.session_state.query_count >= 2:
    st.error("⚠️ Demo limit reached. Come back tomorrow.")
    st.stop()

st.info("ℹ️ Rate limit: 2 queries per session.")

# Chat input (Enter to submit, Shift+Enter for new line)
question = st.chat_input("Ask about customer complaints...")

if question:
    with st.spinner("Searching complaints..."):
        try:
            result = index.search(
                namespace="amazon-reviews",
                query={
                    "inputs": {"text": question},
                    "top_k": 5
                }
            )
            
            hits = result['result']['hits']
            if not hits:
                st.warning("No similar complaints found.")
            else:
                context = "\n".join([hit['fields']['text'] for hit in hits])
                response = llm.chat.completions.create(
                    model="deepseek-chat",
                    messages=[
                        {"role": "system", "content": f"Context from Amazon complaints:\n{context}"},
                        {"role": "user", "content": question}
                    ]
                )
                answer = response.choices[0].message.content
                
                st.success("Answer generated!")
                st.markdown("### 💡 Answer")
                st.write(answer)
                
                st.session_state.query_count += 1
                
                with st.expander("See source complaints"):
                    for hit in hits:
                        st.markdown(f"- {hit['fields']['text']}")
        except Exception as e:
            st.error(f"Error: {e}")
    
    # Show remaining queries (optional)
    remaining = 2 - st.session_state.query_count
    st.caption(f"Remaining queries: {remaining}")