FROM apache/airflow:3.2.2-python3.11

# Install dependencies for sentence-transformers
RUN pip install --no-cache-dir \
    pandas \
    dbt-bigquery \
    sentence-transformers \
    umap-learn \
    hdbscan \
    scikit-learn \
    openai \
    python-dotenv \
    google-cloud-bigquery